select
    lpad(coalesce(cast(round(summary_data.january_min::numeric, 1) as text), '0.0'), 6, ' ') as january_min,
    lpad(coalesce(cast(round(summary_data.january_max::numeric, 1) as text), '0.0'), 6, ' ') as january_max,
    lpad(coalesce(cast(round(summary_data.january_avg::numeric, 1) as text), '0.0'), 6, ' ') as january_avg,
    lpad(coalesce(cast(round(summary_data.february_min::numeric, 1) as text), '0.0'), 6, ' ') as february_min,
    lpad(coalesce(cast(round(summary_data.february_max::numeric, 1) as text), '0.0'), 6, ' ') as february_max,
    lpad(coalesce(cast(round(summary_data.february_avg::numeric, 1) as text), '0.0'), 6, ' ') as february_avg,
    lpad(coalesce(cast(round(summary_data.march_min::numeric, 1) as text), '0.0'), 6, ' ') as march_min,
    lpad(coalesce(cast(round(summary_data.march_max::numeric, 1) as text), '0.0'), 6, ' ') as march_max,
    lpad(coalesce(cast(round(summary_data.march_avg::numeric, 1) as text), '0.0'), 6, ' ') as march_avg,
    lpad(coalesce(cast(round(summary_data.april_min::numeric, 1) as text), '0.0'), 6, ' ') as april_min,
    lpad(coalesce(cast(round(summary_data.april_max::numeric, 1) as text), '0.0'), 6, ' ') as april_max,
    lpad(coalesce(cast(round(summary_data.april_avg::numeric, 1) as text), '0.0'), 6, ' ') as april_avg,
    lpad(coalesce(cast(round(summary_data.may_min::numeric, 1) as text), '0.0'), 6, ' ') as may_min,
    lpad(coalesce(cast(round(summary_data.may_max::numeric, 1) as text), '0.0'), 6, ' ') as may_max,
    lpad(coalesce(cast(round(summary_data.may_avg::numeric, 1) as text), '0.0'), 6, ' ') as may_avg,
    lpad(coalesce(cast(round(summary_data.june_min::numeric, 1) as text), '0.0'), 6, ' ') as june_min,
    lpad(coalesce(cast(round(summary_data.june_max::numeric, 1) as text), '0.0'), 6, ' ') as june_max,
    lpad(coalesce(cast(round(summary_data.june_avg::numeric, 1) as text), '0.0'), 6, ' ') as june_avg,
    lpad(coalesce(cast(round(summary_data.july_min::numeric, 1) as text), '0.0'), 6, ' ') as july_min,
    lpad(coalesce(cast(round(summary_data.july_max::numeric, 1) as text), '0.0'), 6, ' ') as july_max,
    lpad(coalesce(cast(round(summary_data.july_avg::numeric, 1) as text), '0.0'), 6, ' ') as july_avg,
    lpad(coalesce(cast(round(summary_data.august_min::numeric, 1) as text), '0.0'), 6, ' ') as august_min,
    lpad(coalesce(cast(round(summary_data.august_max::numeric, 1) as text), '0.0'), 6, ' ') as august_max,
    lpad(coalesce(cast(round(summary_data.august_avg::numeric, 1) as text), '0.0'), 6, ' ') as august_avg,
    lpad(coalesce(cast(round(summary_data.september_min::numeric, 1) as text), '0.0'), 6, ' ') as september_min,
    lpad(coalesce(cast(round(summary_data.september_max::numeric, 1) as text), '0.0'), 6, ' ') as september_max,
    lpad(coalesce(cast(round(summary_data.september_avg::numeric, 1) as text), '0.0'), 6, ' ') as september_avg,
    lpad(coalesce(cast(round(summary_data.october_min::numeric, 1) as text), '0.0'), 6, ' ') as october_min,
    lpad(coalesce(cast(round(summary_data.october_max::numeric, 1) as text), '0.0'), 6, ' ') as october_max,
    lpad(coalesce(cast(round(summary_data.october_avg::numeric, 1) as text), '0.0'), 6, ' ') as october_avg,
    lpad(coalesce(cast(round(summary_data.november_min::numeric, 1) as text), '0.0'), 6, ' ') as november_min,
    lpad(coalesce(cast(round(summary_data.november_max::numeric, 1) as text), '0.0'), 6, ' ') as november_max,
    lpad(coalesce(cast(round(summary_data.november_avg::numeric, 1) as text), '0.0'), 6, ' ') as november_avg,
    lpad(coalesce(cast(round(summary_data.december_min::numeric, 1) as text), '0.0'), 6, ' ') as december_min,
    lpad(coalesce(cast(round(summary_data.december_max::numeric, 1) as text), '0.0'), 6, ' ') as december_max,
    lpad(coalesce(cast(round(summary_data.december_avg::numeric, 1) as text), '0.0'), 6, ' ') as december_avg,
    lpad(coalesce(cast(round(summary_data.total_min::numeric, 1) as text), '0.0'), 7, ' ') as total_min,
    lpad(coalesce(cast(round(summary_data.total_max::numeric, 1) as text), '0.0'), 7, ' ') as total_max,
    lpad(coalesce(cast(round(summary_data.total_avg::numeric, 1) as text), '0.0'), 7, ' ') as total_avg
from (
  select
    min(yearly_data.january) as january_min,
    max(yearly_data.january) as january_max,
    avg(yearly_data.january) as january_avg,
    min(yearly_data.february) as february_min,
    max(yearly_data.february) as february_max,
    avg(yearly_data.february) as february_avg,
    min(yearly_data.march) as march_min,
    max(yearly_data.march) as march_max,
    avg(yearly_data.march) as march_avg,
    min(yearly_data.april) as april_min,
    max(yearly_data.april) as april_max,
    avg(yearly_data.april) as april_avg,
    min(yearly_data.may) as may_min,
    max(yearly_data.may) as may_max,
    avg(yearly_data.may) as may_avg,
    min(yearly_data.june) as june_min,
    max(yearly_data.june) as june_max,
    avg(yearly_data.june) as june_avg,
    min(yearly_data.july) as july_min,
    max(yearly_data.july) as july_max,
    avg(yearly_data.july) as july_avg,
    min(yearly_data.august) as august_min,
    max(yearly_data.august) as august_max,
    avg(yearly_data.august) as august_avg,
    min(yearly_data.september) as september_min,
    max(yearly_data.september) as september_max,
    avg(yearly_data.september) as september_avg,
    min(yearly_data.october) as october_min,
    max(yearly_data.october) as october_max,
    avg(yearly_data.october) as october_avg,
    min(yearly_data.november) as november_min,
    max(yearly_data.november) as november_max,
    avg(yearly_data.november) as november_avg,
    min(yearly_data.december) as december_min,
    max(yearly_data.december) as december_max,
    avg(yearly_data.december) as december_avg,
    min(yearly_data.total) as total_min,
    max(yearly_data.total) as total_max,
    avg(yearly_data.total) as total_avg
  from (
    select --pivoted.year,
      max(pivoted.january) as january,
      max(pivoted.february) as february,
      max(pivoted.march) as march,
      max(pivoted.april) as april,
      max(pivoted.may) as may,
      max(pivoted.june) as june,
      max(pivoted.july) as july,
      max(pivoted.august) as august,
      max(pivoted.september) as september,
      max(pivoted.october) as october,
      max(pivoted.november) as november,
      max(pivoted.december) as december,
      sum(pivoted.rainfall) as total
    from (
      select rain_data.year as year,
        case when rain_data.month = 1 then rain_data.rainfall else null end as january,
        case when rain_data.month = 2 then rain_data.rainfall else null end as february,
        case when rain_data.month = 3 then rain_data.rainfall else null end as march,
        case when rain_data.month = 4 then rain_data.rainfall else null end as april,
        case when rain_data.month = 5 then rain_data.rainfall else null end as may,
        case when rain_data.month = 6 then rain_data.rainfall else null end as june,
        case when rain_data.month = 7 then rain_data.rainfall else null end as july,
        case when rain_data.month = 8 then rain_data.rainfall else null end as august,
        case when rain_data.month = 9 then rain_data.rainfall else null end as september,
        case when rain_data.month = 10 then rain_data.rainfall else null end as october,
        case when rain_data.month = 11 then rain_data.rainfall else null end as november,
        case when rain_data.month = 12 then rain_data.rainfall else null end as december,
        rain_data.rainfall as rainfall
      from (
        select extract(year from s.time_stamp) as year,
          extract(month from s.time_stamp) as month,
          sum(s.rainfall) as rainfall
        from sample s
        inner join station stn on stn.station_id = s.station_id
        where stn.code = :stationCode
           and s.time_stamp between to_timestamp(:start_t) and to_timestamp(:end_t)
        group by year, month
      ) as rain_data
    ) as pivoted
    group by pivoted.year
  ) as yearly_data
) as summary_data