name: zxweather CI
on: [push]
jobs:
  Desktop-Win32-Debug:
    name: Win32 Desktop Client Build
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.13.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_mingw73'
          install-deps: 'true'
          modules: 'qtscript'
          cached: 'false'
          setup-python: 'true'
          tools: ''
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==1.2.4'
          py7zrversion: '==0.14.0'
          extra: '--external 7z'
      - name: qmake
        run: |
          cd ${{ github.workspace }}
          mkdir build_out
          cd build_out
          qmake ../desktop
          dir /s /b

