name: zxweather CI
on: [push]
jobs:
  Desktop-Windows:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    strategy:
      matrix:
        config:
        - {
            name: "Windows 32bit Qt 5.13.2", 
            artifact: "win32-qt5.13.2-release",
            zip_name: "zxweather-desktop.zip",
            qt: '5.13.2',
            arch: 'win32_mingw73',
            modules: 'qtscript qtmultimedia',
            tools: 'tools_mingw,7.3.0,qt.tools.win32_mingw730',
            compiler_path: "%IQTA_TOOLS%\mingw730_32\bin\"
          }
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.config.qt }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.config.arch }}
          install-deps: 'true'
          modules: ${{ matrix.config.modules }}
          cached: 'false'
          setup-python: 'true'
          tools: ${{ matrix.config.tools }}
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==1.2.4'
          py7zrversion: '==0.14.0'
          extra: '--external 7z'       
      - name: qmake
        run: |
          set PATH=${{matrix.config.compiler_path}};%PATH%
          cd ${{ github.workspace }}
          mkdir build_out
          cd build_out
          qmake ../desktop
        shell: cmd
      - name: Build
        run: |
          set PATH=%${{matrix.config.compiler_path}};%PATH%
          cd ${{ github.workspace }}\build_out
          mingw32-make.exe -j 2
        shell: cmd
      - name: Make distribution
        run: |
          set PATH=${{matrix.config.compiler_path}};%PATH%
          cd ${{ github.workspace }}
          mkdir dist
          cd dist
          copy ..\build_out\release\zxweather.exe
          copy ..\desktop\lib\libpq-9.1-win32\libpq.dll
          copy ..\desktop\lib\libecpg-9.1-win32\*.dll
          copy ..\desktop\qtcolorbutton\license.txt LICENSE.qtcolorbutton
          copy ..\desktop\qtcolorbutton\lgpl-2.1.txt LICENSE.lgpl-2.1
          copy ..\desktop\qtcolorbutton\LGPL_EXCEPTION.txt
          copy ..\desktop\charts\qcp\GPL.txt LICENSE.gpl3
          copy ..\desktop\reporting\qt-mustache\license.txt LICENSE.qt-mustache
          %Qt5_Dir%\bin\windeployqt --compiler-runtime zxweather.exe
          del sqldrivers\qsqlodbc.dll
          copy NUL zxweather.ini
          cd ..
          7z a -tzip "${{artifact.config.zip_name}}" dist
        shell: cmd
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.config.artifact }}
          path: ${{artifact.config.zip_name}}
          if-no-files-found: error
          retention-days: 7
          
